---
title: "0001_first.rmd" 
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

---
LINEAR ALEBRA
---


```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)
```

```{r library, include=FALSE} 
here()
library(tibble)
library("matlib")
devtools::install_github("friendly/matlib") #build_vignettes=TRUE )



```
```{r pkg_install, eval=FALSE	, include=FALSE	 }

# default location IS .libPaths()[[1]]
# source ?  see /tmp/Rt...../downloaded_packages   (deleted at end of sesssion)
install.packages(pkgs="matlib", verbose=TRUE, keep_outputs=TRUE,
								 lib=.libPaths()[[1]] )  
.libPaths()
```


```{r render, eval=FALSE, echo=FALSE	}
p  <- fs::path()
w  <- fs::path_wd()
w
here()
file="0001_first.rmd"
dir="rmd"

ren_pdf(file,dir)
ren_github(file, dir)

#knitr::knit_exit()

# To Render
ren_pdf  <- function(file, dir) {
rmarkdown::render(
									here( dir, file), 
									output_dir="~/Downloads/print_and_delete") 
}
ren_pdf(file, dir)

ren_github  <- function(file, dir) {
rmarkdown::render(
									here(dir, file) 
									output_format="github_document",
									output_dir="~/Downloads/print_and_delete") 
}
ren_github(file, dir)
```


```{r}
here()

## pain-in-ass
#devtools::create("../algebra")
#devtools::create(path="../pkg_linear_algebra" )
```

```{r 2.1_code}
# http://www.bendixcarstensen.com/
t  <- tribble(
						 ~x, ~y,
						 1.0, 3.7,	
						 2.0, 4.2,
						 3.0, 4.9,
						 4.0, 5.7,
						 5.0, 6.0
						 )

t

library(ggplot2)
ggplot(t, aes(x=x, y=y)) +
	geom_point()

# almost a line,  
# but impossible to find B, such y=XB
```


```{r crossprod}
# "crossprod " this is statical term, not geometric
#  :=   T(a) %*% a

# Examples:
a  <- c(1, 0)
b   <- c(0, 1)
crossprod(a)  # T(a) a
crossprod(a,b) # T(a) b

A  <- matrix(c(1,3,2,4), nrow=2)
A
crossprod(A)


a  <- c(1,2,3)
b   <- c(4,5,6)

# inner product
a %*% b


# default  b is column matrix (3 x 1)
# t(a) is now row (1 x 3)
# b t(a)
b %*% t(a)  

# (3 x 1)  (1 x 3)
a %*% t(b)

# 1x3   3x1   -> inner prodcut
t(b) %*% a


k
```

Modify the problem, to y=XB (but B_hat is approx)
```{r}
x  <- t$x
y   <- t$y

# solve for Betas, using LSE formula
crossprod


```

```{r col_means}
A  <-  matrix(c(1,2,3,4,5,6), nrow=3)
A

I  <- c(1,1,1)
mean  <- (1/3)*I %*% A
mean

y  <- c(1,2,3,4,5)
mean  <- (1/length(y)) * c(rep(1, length(y))) %*% y
mean
sd(y)
var(y)

y  <- y -mean
z  <- (1/(length(y)-1))*crossprod(y)
z

```






