
---
#title:  "r knitr::current_input(dir=FALSE	)" 
#title:  `r knitr::current_input(dir=FALSE	)` 
output: 
  pdf_document:
    latex_engine: xelatex
    toc:  TRUE
    toc_depth:  1
fontsize: 12pt
geometry: margin=0.5in,top=0.25in
#  md_document:
#  html_document:
#    toc: true
#  	toc_float: true
#    css: styles.css
---

---
TODO -- replace title, dir etc with R expressions
comments
.

/home/jim/.config/nvim/templates/skeleton.Rmd
comments
---

<!--  commments -->
inline code 
 `r knitr::current_input(dir=FALSE	)`
```{r setup, include=FALSE		}
knitr::opts_chunk$set(echo = TRUE,  comment="      ##",  error=TRUE, collapse=TRUE)

```

```{r library, include=FALSE} 
here()
```

# only work through knitr
```{r file_name_here}
here()
here(knitr::current_input(dir=FALSE	 ))
```

```{r file_name_knitr}
knitr::current_input(dir= FALSE	 )
knitr::current_input(dir= TRUE 	 )
```
```{r render, eval=FALSE, echo=FALSE	}
p  <- fs::path()
w  <- fs::path_wd()
w
here()
file=basename("/home/jim/code/pkg_linear_algebra/0001_tst.Rmd")
dir=""

ren_pdf(file,dir)
ren_github(file, dir)

#knitr::knit_exit()

# To Render
ren_pdf  <- function(file, dir) {
rmarkdown::render(
									here( dir, file), 
									output_dir="~/Downloads/print_and_delete") 
}
ren_pdf(file, dir)

ren_github  <- function(file, dir) {
rmarkdown::render(
									here(dir, file) 
									output_format="github_document",
									output_dir="~/Downloads/print_and_delete") 
}
ren_github(file, dir)
```






